# Generated by Django 3.2.9 on 2021-12-09 05:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fromProfile', models.CharField(blank=True, max_length=25, null=True)),
                ('message_content', models.TextField(blank=True, max_length=300, null=True)),
                ('message_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
