# Generated by Django 3.2.9 on 2021-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='toProfile',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
