# Generated by Django 3.2.8 on 2021-10-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentcollection',
            old_name='post_id',
            new_name='post',
        ),
    ]
