# Generated by Django 3.2.8 on 2021-11-07 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_rename_post_id_commentcollection_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcollection',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
