# Generated by Django 3.2.9 on 2021-11-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='post_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='displaypic',
            field=models.ImageField(blank=True, upload_to='uploads/display_pictures'),
        ),
    ]
