# Generated by Django 3.2.9 on 2021-11-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20211112_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displaypic',
            field=models.ImageField(blank=True, default='uploads/display_pictures/default.png', upload_to='uploads/display_pictures'),
        ),
    ]
